/**
 * Encuestas de Banquetería
 * Matri.AI - Sistema de Matchmaking por Categoría
 */

import { SurveyQuestion } from './types';

// Preguntas para USUARIOS sobre banquetería
export const CATERING_USER_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'catering_u_service_type',
    question: '¿Qué tipo de servicio prefieres?',
    type: 'single',
    options: [
      { id: 'plated', label: 'Servido a la mesa', description: 'Servicio formal' },
      { id: 'buffet', label: 'Buffet', description: 'Variedad y libertad' },
      { id: 'stations', label: 'Estaciones temáticas', description: 'Interactivo y moderno' },
      { id: 'cocktail', label: 'Cóctel / Finger food', description: 'Evento más casual' },
      { id: 'family_style', label: 'Estilo familiar', description: 'Compartido en la mesa' },
    ],
    required: true,
    weight: 20,
  },
  {
    id: 'catering_u_cuisine',
    question: '¿Qué tipo de cocina prefieres?',
    type: 'multiple',
    options: [
      { id: 'chilean', label: 'Chilena tradicional' },
      { id: 'international', label: 'Internacional' },
      { id: 'mediterranean', label: 'Mediterránea' },
      { id: 'asian', label: 'Asiática / Fusión' },
      { id: 'gourmet', label: 'Gourmet / Alta cocina' },
      { id: 'comfort', label: 'Comfort food' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'catering_u_budget_pp',
    question: '¿Cuál es tu presupuesto por persona?',
    type: 'single',
    options: [
      { id: 'under_25k', label: 'Menos de $25.000' },
      { id: '25k_35k', label: '$25.000 - $35.000' },
      { id: '35k_50k', label: '$35.000 - $50.000' },
      { id: '50k_70k', label: '$50.000 - $70.000' },
      { id: 'over_70k', label: 'Más de $70.000' },
    ],
    required: true,
    weight: 20,
  },
  {
    id: 'catering_u_guest_count',
    question: '¿Cuántos invitados tendrás?',
    type: 'single',
    options: [
      { id: 'under_50', label: 'Menos de 50' },
      { id: '50_100', label: '50 - 100' },
      { id: '100_150', label: '100 - 150' },
      { id: '150_200', label: '150 - 200' },
      { id: '200_300', label: '200 - 300' },
      { id: 'over_300', label: 'Más de 300' },
    ],
    required: true,
    weight: 10,
  },
  {
    id: 'catering_u_courses',
    question: '¿Cuántos tiempos de comida?',
    type: 'single',
    options: [
      { id: '2', label: '2 tiempos' },
      { id: '3', label: '3 tiempos' },
      { id: '4', label: '4 tiempos' },
      { id: '5_plus', label: '5 o más tiempos' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_u_cocktail',
    question: '¿Incluirás hora de cóctel?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'catering_u_dietary',
    question: '¿Necesitas opciones especiales?',
    type: 'multiple',
    options: [
      { id: 'vegetarian', label: 'Vegetariana' },
      { id: 'vegan', label: 'Vegana' },
      { id: 'gluten_free', label: 'Sin gluten' },
      { id: 'kosher', label: 'Kosher' },
      { id: 'halal', label: 'Halal' },
      { id: 'none', label: 'Ninguna' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_u_beverages',
    question: '¿Qué bebestibles necesitas?',
    type: 'multiple',
    options: [
      { id: 'soft_drinks', label: 'Bebidas' },
      { id: 'wine', label: 'Vinos' },
      { id: 'beer', label: 'Cerveza' },
      { id: 'cocktails', label: 'Cócteles' },
      { id: 'open_bar', label: 'Barra libre' },
      { id: 'premium_liquor', label: 'Licores premium' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_u_tasting',
    question: '¿Quieres degustación previa?',
    type: 'single',
    options: [
      { id: 'required', label: 'Indispensable' },
      { id: 'preferred', label: 'Preferible' },
      { id: 'not_needed', label: 'No necesario' },
    ],
    required: true,
    weight: 3,
  },
  {
    id: 'catering_u_cake',
    question: '¿Incluir torta de novios?',
    type: 'single',
    options: [
      { id: 'no', label: 'No, tengo otro proveedor' },
      { id: 'simple', label: 'Sí, simple' },
      { id: 'elaborate', label: 'Sí, elaborada' },
      { id: 'dessert_table', label: 'Mesa de postres completa' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_u_staff',
    question: '¿Qué nivel de servicio esperas?',
    type: 'single',
    options: [
      { id: 'basic', label: 'Básico' },
      { id: 'standard', label: 'Estándar' },
      { id: 'premium', label: 'Premium / Garzones dedicados' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_u_setup',
    question: '¿Necesitas montaje de mesas?',
    type: 'boolean',
    required: true,
    weight: 2,
  },
];

// Preguntas para PROVEEDORES de banquetería
export const CATERING_PROVIDER_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'catering_p_service_types',
    question: '¿Qué tipos de servicio ofreces?',
    type: 'multiple',
    options: [
      { id: 'plated', label: 'Servido a la mesa' },
      { id: 'buffet', label: 'Buffet' },
      { id: 'stations', label: 'Estaciones temáticas' },
      { id: 'cocktail', label: 'Cóctel / Finger food' },
      { id: 'family_style', label: 'Estilo familiar' },
    ],
    required: true,
    weight: 20,
  },
  {
    id: 'catering_p_cuisines',
    question: '¿Qué tipos de cocina ofreces?',
    type: 'multiple',
    options: [
      { id: 'chilean', label: 'Chilena tradicional' },
      { id: 'international', label: 'Internacional' },
      { id: 'mediterranean', label: 'Mediterránea' },
      { id: 'asian', label: 'Asiática / Fusión' },
      { id: 'gourmet', label: 'Gourmet / Alta cocina' },
      { id: 'comfort', label: 'Comfort food' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'catering_p_price_pp_min',
    question: 'Precio mínimo por persona (CLP)',
    type: 'number',
    min: 10000,
    max: 200000,
    step: 5000,
    required: true,
    weight: 20,
  },
  {
    id: 'catering_p_price_pp_max',
    question: 'Precio máximo por persona (CLP)',
    type: 'number',
    min: 10000,
    max: 200000,
    step: 5000,
    required: true,
    weight: 0,
  },
  {
    id: 'catering_p_guests_min',
    question: 'Mínimo de invitados que atiendes',
    type: 'number',
    min: 10,
    max: 500,
    required: true,
    weight: 10,
  },
  {
    id: 'catering_p_guests_max',
    question: 'Máximo de invitados que atiendes',
    type: 'number',
    min: 50,
    max: 1000,
    required: true,
    weight: 0,
  },
  {
    id: 'catering_p_courses',
    question: '¿Cuántos tiempos ofreces?',
    type: 'multiple',
    options: [
      { id: '2', label: '2 tiempos' },
      { id: '3', label: '3 tiempos' },
      { id: '4', label: '4 tiempos' },
      { id: '5_plus', label: '5 o más tiempos' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_p_cocktail',
    question: '¿Ofreces servicio de cóctel?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'catering_p_dietary',
    question: '¿Qué opciones especiales manejas?',
    type: 'multiple',
    options: [
      { id: 'vegetarian', label: 'Vegetariana' },
      { id: 'vegan', label: 'Vegana' },
      { id: 'gluten_free', label: 'Sin gluten' },
      { id: 'kosher', label: 'Kosher' },
      { id: 'halal', label: 'Halal' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_p_beverages',
    question: '¿Qué bebestibles ofreces?',
    type: 'multiple',
    options: [
      { id: 'soft_drinks', label: 'Bebidas' },
      { id: 'wine', label: 'Vinos' },
      { id: 'beer', label: 'Cerveza' },
      { id: 'cocktails', label: 'Cócteles' },
      { id: 'open_bar', label: 'Barra libre' },
      { id: 'premium_liquor', label: 'Licores premium' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_p_tasting',
    question: '¿Ofreces degustación previa?',
    type: 'single',
    options: [
      { id: 'yes_free', label: 'Sí, gratis' },
      { id: 'yes_paid', label: 'Sí, con costo' },
      { id: 'no', label: 'No' },
    ],
    required: true,
    weight: 3,
  },
  {
    id: 'catering_p_cake',
    question: '¿Ofreces torta de novios?',
    type: 'single',
    options: [
      { id: 'no', label: 'No' },
      { id: 'simple', label: 'Sí, simple' },
      { id: 'elaborate', label: 'Sí, elaborada' },
      { id: 'dessert_table', label: 'Mesa de postres completa' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_p_staff_levels',
    question: '¿Qué niveles de servicio ofreces?',
    type: 'multiple',
    options: [
      { id: 'basic', label: 'Básico' },
      { id: 'standard', label: 'Estándar' },
      { id: 'premium', label: 'Premium' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'catering_p_setup',
    question: '¿Ofreces montaje de mesas?',
    type: 'boolean',
    required: true,
    weight: 2,
  },
  {
    id: 'catering_p_equipment',
    question: '¿Qué equipamiento incluyes?',
    type: 'multiple',
    options: [
      { id: 'tables', label: 'Mesas' },
      { id: 'chairs', label: 'Sillas' },
      { id: 'tableware', label: 'Vajilla' },
      { id: 'glassware', label: 'Cristalería' },
      { id: 'linens', label: 'Mantelería' },
      { id: 'heating', label: 'Calefacción' },
      { id: 'tents', label: 'Carpas' },
    ],
    required: true,
    weight: 5,
  },
];

