/**
 * Encuestas de Decoración
 * Matri.AI - Sistema de Matchmaking por Categoría
 */

import { SurveyQuestion } from './types';

// Preguntas para USUARIOS sobre decoración
export const DECORATION_USER_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'deco_u_style',
    question: '¿Qué estilo de decoración prefieres?',
    type: 'single',
    options: [
      { id: 'romantic', label: 'Romántico', description: 'Suave y delicado' },
      { id: 'rustic', label: 'Rústico', description: 'Natural y campestre' },
      { id: 'modern', label: 'Moderno / Minimalista', description: 'Líneas limpias' },
      { id: 'classic', label: 'Clásico / Elegante', description: 'Atemporal' },
      { id: 'bohemian', label: 'Bohemio', description: 'Libre y artístico' },
      { id: 'tropical', label: 'Tropical', description: 'Colorido y exótico' },
      { id: 'vintage', label: 'Vintage', description: 'Nostálgico' },
      { id: 'glamorous', label: 'Glamoroso', description: 'Lujoso y brillante' },
    ],
    required: true,
    weight: 25,
  },
  {
    id: 'deco_u_colors',
    question: '¿Qué paleta de colores prefieres?',
    type: 'multiple',
    options: [
      { id: 'white_green', label: 'Blanco y verde' },
      { id: 'pastels', label: 'Pasteles' },
      { id: 'bold', label: 'Colores vivos' },
      { id: 'earth', label: 'Tonos tierra' },
      { id: 'jewel', label: 'Tonos joya' },
      { id: 'monochrome', label: 'Monocromático' },
      { id: 'custom', label: 'Personalizada' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'deco_u_budget',
    question: '¿Cuál es tu presupuesto para decoración?',
    type: 'single',
    options: [
      { id: 'under_500k', label: 'Menos de $500.000' },
      { id: '500k_1m', label: '$500.000 - $1.000.000' },
      { id: '1m_2m', label: '$1.000.000 - $2.000.000' },
      { id: '2m_4m', label: '$2.000.000 - $4.000.000' },
      { id: 'over_4m', label: 'Más de $4.000.000' },
    ],
    required: true,
    weight: 20,
  },
  {
    id: 'deco_u_flowers',
    question: '¿Qué tipo de flores prefieres?',
    type: 'multiple',
    options: [
      { id: 'roses', label: 'Rosas' },
      { id: 'peonies', label: 'Peonías' },
      { id: 'hydrangeas', label: 'Hortensias' },
      { id: 'eucalyptus', label: 'Eucalipto' },
      { id: 'wildflowers', label: 'Flores silvestres' },
      { id: 'tropical', label: 'Tropicales' },
      { id: 'dried', label: 'Flores secas' },
      { id: 'no_preference', label: 'Sin preferencia' },
    ],
    required: true,
    weight: 10,
  },
  {
    id: 'deco_u_bridal_bouquet',
    question: '¿Necesitas ramo de novia?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'deco_u_ceremony_deco',
    question: '¿Necesitas decoración de ceremonia?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'deco_u_table_centerpieces',
    question: '¿Qué tipo de centros de mesa?',
    type: 'single',
    options: [
      { id: 'low', label: 'Bajos' },
      { id: 'tall', label: 'Altos' },
      { id: 'mixed', label: 'Mixtos' },
      { id: 'non_floral', label: 'No florales' },
      { id: 'no_preference', label: 'Sin preferencia' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'deco_u_table_count',
    question: '¿Cuántas mesas tendrás?',
    type: 'single',
    options: [
      { id: 'under_10', label: 'Menos de 10' },
      { id: '10_20', label: '10 - 20' },
      { id: '20_30', label: '20 - 30' },
      { id: 'over_30', label: 'Más de 30' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'deco_u_extras',
    question: '¿Qué elementos adicionales te interesan?',
    type: 'multiple',
    options: [
      { id: 'arch', label: 'Arco de ceremonia' },
      { id: 'backdrop', label: 'Backdrop / Fondo' },
      { id: 'hanging', label: 'Instalaciones colgantes' },
      { id: 'candles', label: 'Velas' },
      { id: 'neon', label: 'Letreros neón' },
      { id: 'balloons', label: 'Globos' },
      { id: 'none', label: 'Ninguno' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'deco_u_rental',
    question: '¿Necesitas arriendo de mobiliario?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
];

// Preguntas para PROVEEDORES de decoración
export const DECORATION_PROVIDER_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'deco_p_styles',
    question: '¿Qué estilos de decoración ofreces?',
    type: 'multiple',
    options: [
      { id: 'romantic', label: 'Romántico' },
      { id: 'rustic', label: 'Rústico' },
      { id: 'modern', label: 'Moderno / Minimalista' },
      { id: 'classic', label: 'Clásico / Elegante' },
      { id: 'bohemian', label: 'Bohemio' },
      { id: 'tropical', label: 'Tropical' },
      { id: 'vintage', label: 'Vintage' },
      { id: 'glamorous', label: 'Glamoroso' },
    ],
    required: true,
    weight: 25,
  },
  {
    id: 'deco_p_color_expertise',
    question: '¿Qué paletas manejas mejor?',
    type: 'multiple',
    options: [
      { id: 'white_green', label: 'Blanco y verde' },
      { id: 'pastels', label: 'Pasteles' },
      { id: 'bold', label: 'Colores vivos' },
      { id: 'earth', label: 'Tonos tierra' },
      { id: 'jewel', label: 'Tonos joya' },
      { id: 'monochrome', label: 'Monocromático' },
      { id: 'custom', label: 'Personalizada' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'deco_p_price_min',
    question: 'Precio mínimo de servicio (CLP)',
    type: 'number',
    min: 100000,
    max: 10000000,
    step: 50000,
    required: true,
    weight: 20,
  },
  {
    id: 'deco_p_price_max',
    question: 'Precio máximo de servicio (CLP)',
    type: 'number',
    min: 100000,
    max: 10000000,
    step: 50000,
    required: true,
    weight: 0,
  },
  {
    id: 'deco_p_flower_types',
    question: '¿Qué tipos de flores trabajas?',
    type: 'multiple',
    options: [
      { id: 'roses', label: 'Rosas' },
      { id: 'peonies', label: 'Peonías' },
      { id: 'hydrangeas', label: 'Hortensias' },
      { id: 'eucalyptus', label: 'Eucalipto' },
      { id: 'wildflowers', label: 'Flores silvestres' },
      { id: 'tropical', label: 'Tropicales' },
      { id: 'dried', label: 'Flores secas' },
    ],
    required: true,
    weight: 10,
  },
  {
    id: 'deco_p_bridal_bouquet',
    question: '¿Ofreces ramo de novia?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'deco_p_ceremony_deco',
    question: '¿Ofreces decoración de ceremonia?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'deco_p_centerpiece_types',
    question: '¿Qué tipos de centros de mesa ofreces?',
    type: 'multiple',
    options: [
      { id: 'low', label: 'Bajos' },
      { id: 'tall', label: 'Altos' },
      { id: 'mixed', label: 'Mixtos' },
      { id: 'non_floral', label: 'No florales' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'deco_p_table_capacity',
    question: 'Máximo de mesas que puedes decorar',
    type: 'number',
    min: 5,
    max: 100,
    required: true,
    weight: 5,
  },
  {
    id: 'deco_p_extras',
    question: '¿Qué elementos adicionales ofreces?',
    type: 'multiple',
    options: [
      { id: 'arch', label: 'Arco de ceremonia' },
      { id: 'backdrop', label: 'Backdrop / Fondo' },
      { id: 'hanging', label: 'Instalaciones colgantes' },
      { id: 'candles', label: 'Velas' },
      { id: 'neon', label: 'Letreros neón' },
      { id: 'balloons', label: 'Globos' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'deco_p_rental',
    question: '¿Ofreces arriendo de mobiliario?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'deco_p_rental_items',
    question: '¿Qué mobiliario arriendas?',
    type: 'multiple',
    options: [
      { id: 'chairs', label: 'Sillas' },
      { id: 'tables', label: 'Mesas' },
      { id: 'lounge', label: 'Mobiliario lounge' },
      { id: 'bars', label: 'Barras' },
      { id: 'lighting', label: 'Iluminación' },
      { id: 'linens', label: 'Mantelería' },
    ],
    required: false,
    weight: 0,
  },
];

