/**
 * Encuestas de DJ/VJ
 * Matri.AI - Sistema de Matchmaking por Categoría
 */

import { SurveyQuestion } from './types';

// Preguntas para USUARIOS sobre DJ/VJ
export const DJ_USER_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'dj_u_genres',
    question: '¿Qué géneros musicales te gustan?',
    type: 'multiple',
    options: [
      { id: 'reggaeton', label: 'Reggaetón' },
      { id: 'pop', label: 'Pop Internacional' },
      { id: 'pop_latino', label: 'Pop Latino' },
      { id: 'cumbia', label: 'Cumbia' },
      { id: 'salsa', label: 'Salsa' },
      { id: 'bachata', label: 'Bachata' },
      { id: 'rock', label: 'Rock' },
      { id: 'electronic', label: 'Electrónica' },
      { id: '80s_90s', label: '80s y 90s' },
      { id: 'disco', label: 'Disco' },
      { id: 'jazz', label: 'Jazz / Lounge' },
      { id: 'romantic', label: 'Baladas / Románticas' },
    ],
    required: true,
    weight: 25,
  },
  {
    id: 'dj_u_style',
    question: '¿Qué estilo de fiesta prefieres?',
    type: 'single',
    options: [
      { id: 'elegant', label: 'Elegante / Sofisticado', description: 'Ambiente refinado' },
      { id: 'party', label: 'Fiesta total', description: 'Máxima energía' },
      { id: 'mixed', label: 'Mezcla de ambos', description: 'Elegante al inicio, fiesta después' },
      { id: 'chill', label: 'Relajado / Lounge', description: 'Ambiente tranquilo' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'dj_u_budget',
    question: '¿Cuál es tu presupuesto para DJ?',
    type: 'single',
    options: [
      { id: 'under_400k', label: 'Menos de $400.000' },
      { id: '400k_600k', label: '$400.000 - $600.000' },
      { id: '600k_900k', label: '$600.000 - $900.000' },
      { id: '900k_1400k', label: '$900.000 - $1.400.000' },
      { id: 'over_1400k', label: 'Más de $1.400.000' },
    ],
    required: true,
    weight: 20,
  },
  {
    id: 'dj_u_hours',
    question: '¿Cuántas horas de música necesitas?',
    type: 'single',
    options: [
      { id: '3', label: '3 horas' },
      { id: '4', label: '4 horas' },
      { id: '5', label: '5 horas' },
      { id: '6', label: '6 horas' },
      { id: 'unlimited', label: 'Sin límite' },
    ],
    required: true,
    weight: 10,
  },
  {
    id: 'dj_u_ceremony_music',
    question: '¿Necesitas música para la ceremonia?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'dj_u_cocktail_music',
    question: '¿Necesitas música para el cóctel?',
    type: 'boolean',
    required: true,
    weight: 3,
  },
  {
    id: 'dj_u_mc',
    question: '¿Necesitas que el DJ anime/presente?',
    type: 'single',
    options: [
      { id: 'no', label: 'No, solo música' },
      { id: 'minimal', label: 'Mínimo', description: 'Solo anuncios importantes' },
      { id: 'moderate', label: 'Moderado', description: 'Animación equilibrada' },
      { id: 'full', label: 'Animación completa', description: 'DJ animador' },
    ],
    required: true,
    weight: 10,
  },
  {
    id: 'dj_u_lighting',
    question: '¿Qué nivel de iluminación necesitas?',
    type: 'single',
    options: [
      { id: 'basic', label: 'Básica', description: 'Luces simples' },
      { id: 'standard', label: 'Estándar', description: 'Buen ambiente' },
      { id: 'premium', label: 'Premium con efectos', description: 'Show de luces' },
      { id: 'custom', label: 'Personalizada', description: 'Diseño a medida' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'dj_u_effects',
    question: '¿Qué efectos especiales te interesan?',
    type: 'multiple',
    options: [
      { id: 'fog', label: 'Máquina de humo' },
      { id: 'cold_sparks', label: 'Chispas frías' },
      { id: 'laser', label: 'Láser' },
      { id: 'confetti', label: 'Confetti' },
      { id: 'bubbles', label: 'Burbujas' },
      { id: 'none', label: 'Ninguno' },
    ],
    required: true,
    weight: 3,
  },
  {
    id: 'dj_u_karaoke',
    question: '¿Te gustaría tener karaoke?',
    type: 'boolean',
    required: true,
    weight: 2,
  },
  {
    id: 'dj_u_requests',
    question: '¿Permitirás solicitudes de invitados?',
    type: 'single',
    options: [
      { id: 'no', label: 'No' },
      { id: 'limited', label: 'Limitadas', description: 'Solo algunas' },
      { id: 'yes', label: 'Sí, todas' },
    ],
    required: true,
    weight: 2,
  },
];

// Preguntas para PROVEEDORES de DJ/VJ
export const DJ_PROVIDER_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'dj_p_genres',
    question: '¿Qué géneros musicales dominas?',
    type: 'multiple',
    options: [
      { id: 'reggaeton', label: 'Reggaetón' },
      { id: 'pop', label: 'Pop Internacional' },
      { id: 'pop_latino', label: 'Pop Latino' },
      { id: 'cumbia', label: 'Cumbia' },
      { id: 'salsa', label: 'Salsa' },
      { id: 'bachata', label: 'Bachata' },
      { id: 'rock', label: 'Rock' },
      { id: 'electronic', label: 'Electrónica' },
      { id: '80s_90s', label: '80s y 90s' },
      { id: 'disco', label: 'Disco' },
      { id: 'jazz', label: 'Jazz / Lounge' },
      { id: 'romantic', label: 'Baladas / Románticas' },
    ],
    required: true,
    weight: 25,
  },
  {
    id: 'dj_p_styles',
    question: '¿Qué estilos de fiesta manejas?',
    type: 'multiple',
    options: [
      { id: 'elegant', label: 'Elegante / Sofisticado' },
      { id: 'party', label: 'Fiesta total' },
      { id: 'mixed', label: 'Mezcla de ambos' },
      { id: 'chill', label: 'Relajado / Lounge' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'dj_p_price_min',
    question: 'Precio mínimo de tu servicio (CLP)',
    type: 'number',
    min: 100000,
    max: 5000000,
    step: 50000,
    required: true,
    weight: 20,
  },
  {
    id: 'dj_p_price_max',
    question: 'Precio máximo de tu servicio (CLP)',
    type: 'number',
    min: 100000,
    max: 5000000,
    step: 50000,
    required: true,
    weight: 0,
  },
  {
    id: 'dj_p_hours_min',
    question: 'Horas mínimas de servicio',
    type: 'number',
    min: 1,
    max: 8,
    required: true,
    weight: 10,
  },
  {
    id: 'dj_p_hours_max',
    question: 'Horas máximas de servicio',
    type: 'number',
    min: 1,
    max: 12,
    required: true,
    weight: 0,
  },
  {
    id: 'dj_p_ceremony_music',
    question: '¿Ofreces música para ceremonia?',
    type: 'boolean',
    required: true,
    weight: 5,
  },
  {
    id: 'dj_p_cocktail_music',
    question: '¿Ofreces música para cóctel?',
    type: 'boolean',
    required: true,
    weight: 3,
  },
  {
    id: 'dj_p_mc_levels',
    question: '¿Qué niveles de animación ofreces?',
    type: 'multiple',
    options: [
      { id: 'no', label: 'Solo música' },
      { id: 'minimal', label: 'Mínimo' },
      { id: 'moderate', label: 'Moderado' },
      { id: 'full', label: 'Animación completa' },
    ],
    required: true,
    weight: 10,
  },
  {
    id: 'dj_p_lighting_levels',
    question: '¿Qué niveles de iluminación ofreces?',
    type: 'multiple',
    options: [
      { id: 'basic', label: 'Básica' },
      { id: 'standard', label: 'Estándar' },
      { id: 'premium', label: 'Premium con efectos' },
      { id: 'custom', label: 'Personalizada' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'dj_p_effects',
    question: '¿Qué efectos especiales ofreces?',
    type: 'multiple',
    options: [
      { id: 'fog', label: 'Máquina de humo' },
      { id: 'cold_sparks', label: 'Chispas frías' },
      { id: 'laser', label: 'Láser' },
      { id: 'confetti', label: 'Confetti' },
      { id: 'bubbles', label: 'Burbujas' },
    ],
    required: true,
    weight: 3,
  },
  {
    id: 'dj_p_karaoke',
    question: '¿Ofreces karaoke?',
    type: 'boolean',
    required: true,
    weight: 2,
  },
  {
    id: 'dj_p_screens',
    question: '¿Ofreces pantallas/proyección?',
    type: 'single',
    options: [
      { id: 'no', label: 'No' },
      { id: 'one', label: 'Una pantalla' },
      { id: 'multiple', label: 'Varias pantallas' },
    ],
    required: true,
    weight: 2,
  },
  {
    id: 'dj_p_equipment_sound',
    question: '¿Qué equipo de sonido tienes?',
    type: 'multiple',
    options: [
      { id: 'small_100', label: 'Hasta 100 personas' },
      { id: 'medium_200', label: 'Hasta 200 personas' },
      { id: 'large_400', label: 'Hasta 400 personas' },
      { id: 'xlarge', label: 'Más de 400 personas' },
      { id: 'subwoofer', label: 'Subwoofers' },
      { id: 'wireless_mic', label: 'Micrófonos inalámbricos' },
    ],
    required: true,
    weight: 5,
  },
];

