/**
 * Encuestas de Vestidos & Trajes
 * Matri.AI - Sistema de Matchmaking por Categoría
 * 
 * Cubre vestidos de novia, trajes de novio, vestuario para cortejo y familia.
 */

import { SurveyQuestion } from './types';

// Preguntas para USUARIOS sobre vestidos y trajes
export const DRESS_USER_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'dress_u_need',
    question: '¿Qué necesitas para tu boda?',
    type: 'multiple',
    options: [
      { id: 'bride_dress', label: 'Vestido de novia', description: 'Para la novia' },
      { id: 'groom_suit', label: 'Traje de novio', description: 'Para el novio' },
      { id: 'bridesmaids', label: 'Vestidos de damas de honor', description: 'Para las damas' },
      { id: 'groomsmen', label: 'Trajes de padrinos', description: 'Para los padrinos' },
      { id: 'flower_girl', label: 'Vestuario pajes/damitas', description: 'Para niños del cortejo' },
      { id: 'mother_bride', label: 'Vestido madre de la novia', description: 'Para la madre' },
      { id: 'mother_groom', label: 'Vestido madre del novio', description: 'Para la suegra' },
      { id: 'accessories', label: 'Solo accesorios', description: 'Velos, tocados, zapatos, etc.' },
    ],
    required: true,
    weight: 25,
  },
  {
    id: 'dress_u_bride_style',
    question: '¿Qué estilo de vestido de novia prefieres?',
    type: 'multiple',
    options: [
      { id: 'classic', label: 'Clásico / Tradicional', description: 'Elegancia atemporal' },
      { id: 'romantic', label: 'Romántico', description: 'Encajes, tules, detalles delicados' },
      { id: 'modern', label: 'Moderno / Minimalista', description: 'Líneas limpias y simples' },
      { id: 'bohemian', label: 'Bohemio', description: 'Libre, fluido, natural' },
      { id: 'glamorous', label: 'Glamoroso', description: 'Brillos, pedrería, impactante' },
      { id: 'vintage', label: 'Vintage', description: 'Estilo de otra época' },
      { id: 'princess', label: 'Princesa', description: 'Falda voluminosa, cuento de hadas' },
      { id: 'sexy', label: 'Sensual', description: 'Escotes, transparencias, ajustado' },
    ],
    required: true,
    weight: 20,
    // CAMBIO: Solo mostrar si seleccionó vestido de novia
    dependsOn: {
      questionId: 'dress_u_need',
      values: ['bride_dress'],
    },
  },
  {
    id: 'dress_u_bride_silhouette',
    question: '¿Qué silueta de vestido prefieres?',
    type: 'multiple',
    options: [
      { id: 'a_line', label: 'Línea A', description: 'Ajustado arriba, suelto abajo' },
      { id: 'ballgown', label: 'Corte princesa / Ball gown', description: 'Falda muy amplia' },
      { id: 'mermaid', label: 'Sirena', description: 'Ajustado hasta la rodilla, luego se abre' },
      { id: 'sheath', label: 'Recto / Columna', description: 'Sigue la línea del cuerpo' },
      { id: 'empire', label: 'Imperio', description: 'Corte bajo el busto' },
      { id: 'trumpet', label: 'Trompeta', description: 'Ajustado hasta el muslo' },
      { id: 'tea_length', label: 'Midi / Té', description: 'Largo hasta la pantorrilla' },
      { id: 'mini', label: 'Corto', description: 'Sobre la rodilla' },
      { id: 'no_preference', label: 'Sin preferencia' },
    ],
    required: true,
    weight: 15,
    // CAMBIO: Solo mostrar si seleccionó vestido de novia
    dependsOn: {
      questionId: 'dress_u_need',
      values: ['bride_dress'],
    },
  },
  {
    id: 'dress_u_groom_style',
    question: '¿Qué estilo de traje para el novio?',
    type: 'single',
    options: [
      { id: 'classic_suit', label: 'Traje clásico', description: 'Elegante y formal' },
      { id: 'tuxedo', label: 'Smoking / Tuxedo', description: 'Máxima formalidad' },
      { id: 'modern', label: 'Moderno / Slim fit', description: 'Corte contemporáneo' },
      { id: 'casual', label: 'Semi-formal', description: 'Más relajado' },
      { id: 'vintage', label: 'Vintage', description: 'Estilo retro' },
      { id: 'destination', label: 'Para boda destino', description: 'Lino, colores claros' },
      { id: 'not_needed', label: 'No necesito traje de novio' },
    ],
    required: true,
    weight: 15,
    // CAMBIO: Solo mostrar si seleccionó traje de novio
    dependsOn: {
      questionId: 'dress_u_need',
      values: ['groom_suit'],
    },
  },
  {
    id: 'dress_u_service_type',
    question: '¿Qué tipo de servicio prefieres?',
    type: 'single',
    options: [
      { id: 'buy_new', label: 'Comprar nuevo', description: 'Vestido/traje nuevo' },
      { id: 'custom', label: 'Diseño a medida', description: 'Hecho especialmente para ti' },
      { id: 'rent', label: 'Arriendo', description: 'Alquilar para el día' },
      { id: 'second_hand', label: 'Segunda mano / Outlet', description: 'Vestidos usados o de muestra' },
      { id: 'alterations', label: 'Solo ajustes/arreglos', description: 'Ya tengo vestido, necesito modificaciones' },
      { id: 'no_preference', label: 'Sin preferencia' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'dress_u_budget_bride',
    question: '¿Cuál es tu presupuesto para el vestido de novia?',
    type: 'single',
    options: [
      { id: 'under_500k', label: 'Menos de $500.000' },
      { id: '500k_1m', label: '$500.000 - $1.000.000' },
      { id: '1m_2m', label: '$1.000.000 - $2.000.000' },
      { id: '2m_3m', label: '$2.000.000 - $3.000.000' },
      { id: '3m_5m', label: '$3.000.000 - $5.000.000' },
      { id: 'over_5m', label: 'Más de $5.000.000' },
      { id: 'skip', label: 'Omitir' },
    ],
    required: true,
    weight: 15,
    // CAMBIO: Solo mostrar si seleccionó vestido de novia
    dependsOn: {
      questionId: 'dress_u_need',
      values: ['bride_dress'],
    },
  },
  {
    id: 'dress_u_budget_groom',
    question: '¿Cuál es tu presupuesto para el traje de novio?',
    type: 'single',
    options: [
      { id: 'under_200k', label: 'Menos de $200.000' },
      { id: '200k_400k', label: '$200.000 - $400.000' },
      { id: '400k_700k', label: '$400.000 - $700.000' },
      { id: '700k_1m', label: '$700.000 - $1.000.000' },
      { id: 'over_1m', label: 'Más de $1.000.000' },
      { id: 'skip', label: 'Omitir / No necesito' },
    ],
    required: true,
    weight: 10,
    // CAMBIO: Solo mostrar si seleccionó traje de novio
    dependsOn: {
      questionId: 'dress_u_need',
      values: ['groom_suit'],
    },
  },
  {
    id: 'dress_u_timeline',
    question: '¿Cuánto tiempo tienes antes de la boda?',
    type: 'single',
    options: [
      { id: 'under_3m', label: 'Menos de 3 meses' },
      { id: '3_6m', label: '3 - 6 meses' },
      { id: '6_9m', label: '6 - 9 meses' },
      { id: '9_12m', label: '9 - 12 meses' },
      { id: 'over_12m', label: 'Más de 1 año' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'dress_u_accessories',
    question: '¿Qué accesorios necesitas?',
    type: 'multiple',
    options: [
      { id: 'veil', label: 'Velo' },
      { id: 'tiara', label: 'Tiara / Corona' },
      { id: 'headpiece', label: 'Tocado / Peineta' },
      { id: 'shoes', label: 'Zapatos' },
      { id: 'jewelry', label: 'Joyería (aretes, collar, etc.)' },
      { id: 'belt', label: 'Cinturón / Faja' },
      { id: 'jacket', label: 'Chaqueta / Capa' },
      { id: 'none', label: 'Ninguno / Ya los tengo' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'dress_u_fitting',
    question: '¿Necesitas pruebas y ajustes incluidos?',
    type: 'single',
    options: [
      { id: 'required', label: 'Indispensable', description: 'Varias pruebas hasta quedar perfecto' },
      { id: 'preferred', label: 'Preferible', description: 'Al menos una prueba' },
      { id: 'not_needed', label: 'No necesario', description: 'Confío en las medidas' },
    ],
    required: true,
    weight: 5,
  },
];

// Preguntas para PROVEEDORES de vestidos y trajes
export const DRESS_PROVIDER_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'dress_p_services',
    question: '¿Qué servicios de vestuario ofreces?',
    type: 'multiple',
    options: [
      { id: 'bride_dress', label: 'Vestidos de novia' },
      { id: 'groom_suit', label: 'Trajes de novio' },
      { id: 'bridesmaids', label: 'Vestidos de damas de honor' },
      { id: 'groomsmen', label: 'Trajes de padrinos' },
      { id: 'flower_girl', label: 'Vestuario pajes/damitas' },
      { id: 'mother_outfits', label: 'Vestidos para madres' },
      { id: 'accessories', label: 'Accesorios (velos, tocados, etc.)' },
      { id: 'shoes', label: 'Zapatos de novia/novio' },
    ],
    required: true,
    weight: 25,
  },
  {
    id: 'dress_p_bride_styles',
    question: '¿Qué estilos de vestido de novia manejas?',
    type: 'multiple',
    options: [
      { id: 'classic', label: 'Clásico / Tradicional' },
      { id: 'romantic', label: 'Romántico' },
      { id: 'modern', label: 'Moderno / Minimalista' },
      { id: 'bohemian', label: 'Bohemio' },
      { id: 'glamorous', label: 'Glamoroso' },
      { id: 'vintage', label: 'Vintage' },
      { id: 'princess', label: 'Princesa' },
      { id: 'sexy', label: 'Sensual' },
    ],
    required: true,
    weight: 20,
  },
  {
    id: 'dress_p_silhouettes',
    question: '¿Qué siluetas de vestido ofreces?',
    type: 'multiple',
    options: [
      { id: 'a_line', label: 'Línea A' },
      { id: 'ballgown', label: 'Corte princesa / Ball gown' },
      { id: 'mermaid', label: 'Sirena' },
      { id: 'sheath', label: 'Recto / Columna' },
      { id: 'empire', label: 'Imperio' },
      { id: 'trumpet', label: 'Trompeta' },
      { id: 'tea_length', label: 'Midi / Té' },
      { id: 'mini', label: 'Corto' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'dress_p_groom_styles',
    question: '¿Qué estilos de traje de novio ofreces?',
    type: 'multiple',
    options: [
      { id: 'classic_suit', label: 'Traje clásico' },
      { id: 'tuxedo', label: 'Smoking / Tuxedo' },
      { id: 'modern', label: 'Moderno / Slim fit' },
      { id: 'casual', label: 'Semi-formal' },
      { id: 'vintage', label: 'Vintage' },
      { id: 'destination', label: 'Para boda destino' },
      { id: 'none', label: 'No ofrezco trajes de novio' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'dress_p_service_types',
    question: '¿Qué tipos de servicio ofreces?',
    type: 'multiple',
    options: [
      { id: 'buy_new', label: 'Venta de nuevos' },
      { id: 'custom', label: 'Diseño a medida' },
      { id: 'rent', label: 'Arriendo' },
      { id: 'second_hand', label: 'Segunda mano / Outlet' },
      { id: 'alterations', label: 'Ajustes y arreglos' },
    ],
    required: true,
    weight: 15,
  },
  {
    id: 'dress_p_price_bride_min',
    question: 'Precio mínimo vestido de novia (CLP)',
    type: 'number',
    min: 100000,
    max: 10000000,
    step: 50000,
    required: true,
    weight: 15,
  },
  {
    id: 'dress_p_price_bride_max',
    question: 'Precio máximo vestido de novia (CLP)',
    type: 'number',
    min: 200000,
    max: 20000000,
    step: 50000,
    required: true,
    weight: 0,
  },
  {
    id: 'dress_p_price_groom_min',
    question: 'Precio mínimo traje de novio (CLP)',
    type: 'number',
    min: 50000,
    max: 3000000,
    step: 25000,
    required: true,
    weight: 10,
  },
  {
    id: 'dress_p_price_groom_max',
    question: 'Precio máximo traje de novio (CLP)',
    type: 'number',
    min: 100000,
    max: 5000000,
    step: 25000,
    required: true,
    weight: 0,
  },
  {
    id: 'dress_p_accessories',
    question: '¿Qué accesorios ofreces?',
    type: 'multiple',
    options: [
      { id: 'veil', label: 'Velos' },
      { id: 'tiara', label: 'Tiaras / Coronas' },
      { id: 'headpiece', label: 'Tocados / Peinetas' },
      { id: 'shoes', label: 'Zapatos' },
      { id: 'jewelry', label: 'Joyería' },
      { id: 'belt', label: 'Cinturones / Fajas' },
      { id: 'jacket', label: 'Chaquetas / Capas' },
      { id: 'none', label: 'No ofrezco accesorios' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'dress_p_fittings',
    question: '¿Cuántas pruebas incluyes?',
    type: 'single',
    options: [
      { id: '1', label: '1 prueba' },
      { id: '2', label: '2 pruebas' },
      { id: '3', label: '3 pruebas' },
      { id: 'unlimited', label: 'Ilimitadas hasta quedar perfecto' },
      { id: 'extra_cost', label: 'Pruebas adicionales con costo' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'dress_p_alterations',
    question: '¿Incluyes ajustes y arreglos?',
    type: 'single',
    options: [
      { id: 'yes_included', label: 'Sí, incluidos en el precio' },
      { id: 'yes_extra', label: 'Sí, con costo adicional' },
      { id: 'basic_only', label: 'Solo ajustes básicos incluidos' },
      { id: 'no', label: 'No, deben hacerse aparte' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'dress_p_lead_time',
    question: '¿Cuánto tiempo necesitas de anticipación?',
    type: 'single',
    options: [
      { id: 'under_2m', label: 'Menos de 2 meses' },
      { id: '2_4m', label: '2 - 4 meses' },
      { id: '4_6m', label: '4 - 6 meses' },
      { id: '6_9m', label: '6 - 9 meses' },
      { id: 'over_9m', label: 'Más de 9 meses' },
    ],
    required: true,
    weight: 5,
  },
  {
    id: 'dress_p_designers',
    question: '¿Trabajas con diseñadores o marcas específicas?',
    type: 'single',
    options: [
      { id: 'yes_exclusive', label: 'Sí, marcas exclusivas' },
      { id: 'yes_various', label: 'Sí, varias marcas' },
      { id: 'own_designs', label: 'Diseños propios' },
      { id: 'no', label: 'No, sin marca específica' },
    ],
    required: true,
    weight: 0,
  },
  {
    id: 'dress_p_appointment',
    question: '¿Cómo funciona la atención?',
    type: 'single',
    options: [
      { id: 'appointment_only', label: 'Solo con cita previa' },
      { id: 'walk_in', label: 'Sin cita, horario tienda' },
      { id: 'both', label: 'Ambas opciones' },
      { id: 'home_service', label: 'Atención a domicilio' },
    ],
    required: true,
    weight: 0,
  },
];





